### ISSUE TITLE
injectScript should call gtmOnSuccess and gtmOnFailure

### ISSUE THREAD

**Issue by philpott** [poptins/poptin-tagmanager#1]
https://github.com/poptins/poptin-tagmanager/blob/ce22910b2356dca3b0dd7aa975f997cc8ae030f1/template.tpl#L63

The way the tag is coded now gtmOnSuccess will always fire. I would advise updating the code to be

```
if (query('inject_script', url)) {
  injectScript(url, () => {
    log('Loaded');
    // Call data.gtmOnSuccess when the tag is finished.
    data.gtmOnSuccess();
  }, data.gtmOnFailure);
}

```

**Comment by ravi2448** [comment]
its done

**Comment by ravi2448** [comment]
code changed..please check

**Comment by philpott** [comment]
Looks good thanks!
