### ISSUE TITLE
Use encodeUriComponent

### ISSUE THREAD

**Issue by philpott** [poptins/poptin-tagmanager#2]
https://github.com/poptins/poptin-tagmanager/blob/ce22910b2356dca3b0dd7aa975f997cc8ae030f1/template.tpl#L61

The user id parameter should be encoded using encodeUriComponent

**Comment by ravi2448** [comment]
Its done

**Comment by ravi2448** [comment]
it was already done.
const url = 'https://cdn.popt.in/pixel.js?id='+encodeUriComponent(data.userId);

is it not showing you?

**Comment by philpott** [comment]
Sorry missed that -- I think i was comparing it against the original template you submitted (ravi2448/poptin-tagmanager)
